"""empty message

Revision ID: 82446b4bfa78
Revises: 
Create Date: 2025-06-15 19:44:52.646870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82446b4bfa78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'ADMIN', name='statusenum'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contrats',
    sa.Column('id_contrat', sa.Integer(), nullable=False),
    sa.Column('numero_contrat', sa.String(length=50), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_contrat'),
    sa.UniqueConstraint('numero_contrat')
    )
    op.create_table('paiements',
    sa.Column('id_paiement', sa.Integer(), nullable=False),
    sa.Column('id_contrat', sa.Integer(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_contrat'], ['contrats.id_contrat'], ),
    sa.PrimaryKeyConstraint('id_paiement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    op.drop_table('contrats')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
